services:
  - type: web
    name: kantrello
    runtime: ruby
    plan: free
    buildCommand: |
      bundle install
      npm ci --production=false || npm install
      npm run build
      RAILS_ENV=production bundle exec rake assets:precompile
      RAILS_ENV=production bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kantrello-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: kantrello-db
    plan: free
    databaseName: kantrello_production
    user: kantrello
